"""Finalize event database model

Revision ID: 06d42936fdc8
Revises: 30400ea486fb
Create Date: 2022-02-19 23:06:15.291220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06d42936fdc8'
down_revision = '30400ea486fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('slug', sa.String(length=128), nullable=True))
    op.add_column('event', sa.Column('performers', sa.String(length=128), nullable=True))
    op.add_column('event', sa.Column('date', sa.String(length=25), nullable=True))
    op.add_column('event', sa.Column('time', sa.String(length=20), nullable=True))
    op.add_column('event', sa.Column('description', sa.String(length=250), nullable=True))
    op.add_column('event', sa.Column('image', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'image')
    op.drop_column('event', 'description')
    op.drop_column('event', 'time')
    op.drop_column('event', 'date')
    op.drop_column('event', 'performers')
    op.drop_column('event', 'slug')
    # ### end Alembic commands ###
