"""Use date column

Revision ID: 3421bda001a2
Revises: 06d42936fdc8
Create Date: 2022-02-23 13:57:42.389070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3421bda001a2'
down_revision = '06d42936fdc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'date',
               existing_type=sa.DATE())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'date',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)
    # ### end Alembic commands ###
