"""add_event_user_relationship

Revision ID: 35167a36eeb9
Revises: e882c60c5b78
Create Date: 2022-02-26 08:35:49.234806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "35167a36eeb9"
down_revision = "e882c60c5b78"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("event", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_index(op.f("ix_event_user_id"), "event", ["user_id"], unique=False)
    op.create_foreign_key("event_user_user_id_fk", "event", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("event_user_user_id_fk", "event", type_="foreignkey")
    op.drop_index(op.f("ix_event_user_id"), table_name="event")
    op.drop_column("event", "user_id")
    # ### end Alembic commands ###
