"""Add new rating

Revision ID: 43db78001ecb
Revises: f5b40ad179b9
Create Date: 2022-03-09 17:44:20.915708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43db78001ecb'
down_revision = 'f5b40ad179b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
  
    # ### end Alembic commands ###
    op.create_table('rating',
      sa.Column('id', sa.Integer(), nullable=False),
      sa.Column('rating', sa.Integer(), nullable=False),
      sa.Column('created_at', sa.String(length=255), nullable=True),
      sa.Column('event_id',sa.Integer(), nullable=False),
      sa.Column('user_id',sa.Integer(), nullable=False),
      sa.PrimaryKeyConstraint('id'),
      sa.ForeignKeyConstraint(['event_id'],['event.id']),
      sa.ForeignKeyConstraint(['user_id'],['user.id']),

     
     )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')

    # ### end Alembic commands ###
