"""Add event_id column to comments

Revision ID: f5b40ad179b9
Revises: 35167a36eeb9
Create Date: 2022-03-07 17:33:52.130945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5b40ad179b9'
down_revision = '35167a36eeb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('comment', sa.Column('event_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_comment_event_id'), 'comment',['event_id'], unique=False)
    op.create_foreign_key('comment_event_event_id_fk', 'comment', 'event', ['event_id'], ['id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    
    op.drop_constraint('comment_event_event_id_fk', 'comment', type_='foreignkey')
    op.drop_index(op.f('ix_comment_event_id'), table_name='comment')
    op.drop_column('comment','event_id')

    # ### end Alembic commands ###
